name: ner_ehr
channels:
  - conda-forge
dependencies:
  - black
  - flake8
  - ipykernel=5.5.5
  - jupyterlab=3.2.2
  - pip=21.3.1
  - python=3.6.9
  - pip:
    - scispacy
    - https://s3-us-west-2.amazonaws.com/ai2-s2-scispacy/releases/v0.4.0/en_ner_bc5cdr_md-0.4.0.tar.gz
