name: ner_ehr
channels:
  - conda-forge
dependencies:
  - black
  - flake8
  - gensim
  - ipykernel=5.5.5
  - isort
  - ipywidgets
  - jupyterlab=3.2.2
  - jupyterlab_widgets
  - matplotlib
  - nltk
  - numpy
  - pandera
  - pandas
  - pip=21.3.1
  - python=3.6.9
  - seaborn
  - scikit-learn
  - pip:
    - pytorch-lightning
    - scispacy
    - https://s3-us-west-2.amazonaws.com/ai2-s2-scispacy/releases/v0.4.0/en_ner_bc5cdr_md-0.4.0.tar.gz
    - torch
